CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(60) NOT NULL  ,
  `username` VARCHAR(60) NOT NULL UNIQUE ,
  `email` VARCHAR(100) NOT NULL UNIQUE ,
  `phoneNumber` VARCHAR(255)  UNIQUE ,
  `age` INT   ,
  `isCompany` TINYINT(1) NOT NULL  DEFAULT '',
  `domain` VARCHAR(50)   ,
  `password` VARCHAR(60) NOT NULL  DEFAULT '0123456789',
  `inviteCode` INT NOT NULL  ,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);